# -*- coding: utf-8 -*-
"""knn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vpZ2bEsIpnzZPkWXXKKtyBH4SRIw4M32
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris # Import the loader
from sklearn.neighbors import KNeighborsClassifier

# Load the dataset to define the 'iris' variable
iris = load_iris()

#The dataset includes two sepal features which are sepal length and sepal width
X = iris.data[:, :2]
y = iris.target

# Define the neighbor values to evaluate [cite: 55]
k_values = [1, 3, 5, 10]

# The code creates a 2x2 subplot figure which will display two plots next to each other
fig, subplots = plt.subplots(2, 2, figsize=(12, 10))

for i, k in enumerate(k_values):
    # The kNN model first requires initialization followed by training
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X, y)

    # The code creates a coordinate mesh grid to color the decision regions
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.02), np.arange(y_min, y_max, 0.02))

    # The model predicts the class for every point in the mesh grid
    Z = knn.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)

    # The current subplot for display will use the loop index to select which one to show
    ax = subplots[i // 2, i % 2]

    # The code displays decision boundaries through filled contour plots
    ax.contourf(xx, yy, Z, alpha=0.3)

    # The original training data points will be displayed on the graph
    ax.scatter(X[:, 0], X[:, 1], c=y, edgecolor='k', s=20)
    ax.set_title(f"kNN Decision Boundary (k={k})")

# The code organizes the layout before showing the content
plt.tight_layout()
plt.show()