# -*- coding: utf-8 -*-
"""max_depth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IRu6OGUWlbKaYES6G6UXD9kg-12_gHKo
"""

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load the data
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=42)

# Training and evaluating for different depths
for depth in [1, 2, 3]:
    clf = DecisionTreeClassifier(max_depth=depth, random_state=42)
    clf.fit(X_train, y_train)

    train_acc = accuracy_score(y_train, clf.predict(X_train))
    test_acc = accuracy_score(y_test, clf.predict(X_test))

    print(f"Max Depth {depth}: Training Acc = {train_acc:.4f}, Test Acc = {test_acc:.4f}")